---
name: vault

instance_groups:
- name: vault
  instances: 1
  persistent_disk: 4096
  stemcell: trusty
  vm_type: default
  vm_extensions: [vault-lb]
  networks:
  - name: default
    static_ips:
    - ((vault_ip))
  stemcell: trusty
  azs: [z1,z2,z3]
  jobs:
  - name: vault
    release: vault
    properties:
      vault:
        config: |
          storage "file" {
            path = "/var/vcap/store/vault/data"
          }
          listener "tcp" {
            address = "0.0.0.0:8200"
            tls_cert_file = "/var/vcap/jobs/vault/tls/vault/cert.pem"
            tls_key_file  = "/var/vcap/jobs/vault/tls/vault/key.pem"
            tls_min_version = "tls12"
          }
      tls:
        - name: vault
          cert: ((vault-tls.certificate))((vault-ca.certificate))
          key: ((vault-tls.private_key))
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-60000

variables:
- name: vault-ca
  type: certificate
  options:
    is_ca: true
    common_name: vaultCA
- name: vault-tls
  type: certificate
  options:
    ca: vault-ca
    common_name: vault
    extended_key_usage:
    - client_auth
    - server_auth
    alternative_names:
    - 127.0.0.1
    - "*.vault.default.vault.bosh"



releases:
- name: vault
  version: latest

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-30000
  max_in_flight: 50
  serial: false
  update_watch_time: 1000-30000
