---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-pcf-utils

inputs:
  - name: concourse-workshop-repos

params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  MAX_IN_FLIGHT: 1

run:
  path: concourse-workshop-repos/day-3/tasks/repave-diego-cell/task.sh
